image: python:3

stages:
  - test
  - deploy

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user -e .[testing]
  - pip install --user twine
  - python setup.py sdist

pytest2:
  image: python:2
  script:
    - python -m pytest castepinput/tests

pytest3:
  image: python:3
  script:
    - python -m pytest castepinput/tests

stage_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGE_USERNAME
    TWINE_PASSWORD: $STAGE_PASSWORD
  script:
    - twine check dist/*
    - twine upload --repository-url $PACKAGR_REPOSITORY_URL dist/*
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine check dist/*
    - twine upload dist/*
  only:
    - tags
